// LearnOpenGL 中文导读
// 职责：把仓库相对资源路径解析为可供纹理、模型和字体加载器使用的路径。
// 解析优先级：首次调用时缓存 LOGL_ROOT_PATH；未设置时使用 CMake 生成的 logl_root，二者皆空才相对当前工作目录回退。
// 调用边界：只拼接并返回字符串，不验证文件存在，也不改变进程工作目录或 Shader 的相对查找规则。
#ifndef FILESYSTEM_H
#define FILESYSTEM_H

#include <string>
#include <cstdlib>
#include "root_directory.h" // This is a configuration file generated by CMake.

class FileSystem
{
private:
  typedef std::string (*Builder) (const std::string& path);

public:
  static std::string getPath(const std::string& path)
  {
	// Builder 只在第一次调用时选择，因此运行中再修改环境变量不会改变解析策略。
    static std::string(*pathBuilder)(std::string const &) = getPathBuilder();
    return (*pathBuilder)(path);
  }

private:
  static std::string const & getRoot()
  {
	// root_directory.h 由 CMake 写入源码根目录；环境变量可覆盖该配置时路径。
    static char const * envRoot = getenv("LOGL_ROOT_PATH");
    static char const * givenRoot = (envRoot != nullptr ? envRoot : logl_root);
    static std::string root = (givenRoot != nullptr ? givenRoot : "");
    return root;
  }

  //static std::string(*foo (std::string const &)) getPathBuilder()
  static Builder getPathBuilder()
  {
    if (getRoot() != "")
      return &FileSystem::getPathRelativeRoot;
    else
      return &FileSystem::getPathRelativeBinary;
  }

  static std::string getPathRelativeRoot(const std::string& path)
  {
    return getRoot() + std::string("/") + path;
  }

  static std::string getPathRelativeBinary(const std::string& path)
  {
	// 兜底路径依赖启动时工作目录层级，IDE 或自定义输出目录下可能不成立。
    return "../../../" + path;
  }


};

// FILESYSTEM_H
#endif
